"""EvoEquiLang: a typed DSL for equivariant neural architectures."""

from .ast import ArchitectureProgram, InputPort, Node, OutputPort
from .canonicalize import BACKEND_SEMANTICS_VERSION, COMPILER_SEMANTICS_VERSION, architecture_id, canonicalize
from .checkpoint import CHECKPOINT_MAPPING_VERSION, CheckpointMappingError, CheckpointMappingManifest, CheckpointTensorGroup, ReconstructedTensorContract, export_source_state_dict, extract_checkpoint_state_dict, load_mapped_checkpoint_state_dict, normalize_checkpoint_prefixes, translate_checkpoint_state_dict
from .compiler import Compiler, LoweringPlan
from .completion import AvailableValue, CompletionAction, CompletionDistance, HoleSink, TypedHole, complete_typed_hole, materialize_completion_patch, program_completion_frontier
from .cost import CostEstimate, enforce_static_resource_contract, estimate_static_cost
from .diagnostics import DSLValidationError, Diagnostic
from .evidence_store import EvidenceStore
from .factors import CapabilityProfile, LeafFactorDefinition, equiformer_v1_capability_profile, factor_by_region, validate_unique_factor_ownership
from .groups import GroupSpec
from .inference import InferenceResult, TypeChecker
from .irreps import Irrep, Irreps
from .language import LanguageVersion, VocabularyDecision, describe_active_vocabulary, describe_vocabulary_names, select_active_vocabulary
from .language_evolution import LanguageEvolutionBoundary, LanguageEvolutionPreregistration, LanguageEvolutionResult, MotifAdmissionRecord, run_language_evolution_boundary
from .llm_protocol import EvidenceItem, parse_patch_response, parse_planner_response, parse_region_critic_response, parse_region_router_response, planner_prompt, region_critic_prompt, region_critic_repair_prompt, region_router_prompt, repair_prompt, synthesizer_prompt
from .motifs import MotifDefinition, MotifRegistry, expand_motifs
from .migration import ExplicitTopologyMigrationManifest, ExplicitTopologyMigrationResult, MIGRATION_POLICY_VERSION, TypeMigrationManifest, TypeMigrationResult, legacy_equivariant_view, migrate_message_flow_to_explicit_topology, migrate_program_v1_to_v2, migrate_task_contract_v1_to_v2, migrate_value_type_v1_to_v2
from .motif_discovery import CandidateLineageEvidence, LanguageReplayResult, MotifDiscoveryPolicy, MotifDiscoveryReport, MotifProposal, TypedSubgraphOccurrence, discover_motif_proposals, enumerate_typed_subgraphs, fold_occurrence, replay_motif_proposal
from .patch import PatchEdit, TypedPatch, apply_typed_patch, patch_protocol_schema
from .parameters import PARAMETER_CONTRACT_SCHEMA_VERSION, ParameterAxis, ParameterContract
from .reference_motifs import reference_motif_registry
from .reference_programs import equiformer_v3_attention_program, equiformer_v3_backbone_program, equiformer_v3_direct_model_program, equiformer_v3_energy_head_program, equiformer_v3_energy_model_program, equiformer_v3_feed_forward_program, equiformer_v3_force_head_program, equiformer_v3_input_program, equiformer_v3_transblock_program, import_equiformer_v1, import_equiformer_v3
from .repair_completion import completion_repair_suggestions
from .regions import RegionDefinition, frozen_complement_hash, validate_region_transition, v1_region_registry
from .rewrites import RewriteRuleDescriptor, RewriteStep, StrictRewriteResult, apply_strict_rewrites, strict_rewrite_registry_hash
from .registry import PrimitiveRegistry, core_registry
from .task import ResourceContract, TaskContract, task_reasoning_context, validate_task_reasoning
from .search import DSLGenerationEngine, GenerationResult
from .search_surface import CanonicalSearchSurface, SEARCH_SURFACE_VERSION, default_canonical_search_surface
from .types import AffinePointType, AxisSpec, Carrier, CategoricalTensorType, EquivarianceLevel, EquivariantTensorType, EquivariantType, FeatureRole, Frame, GraphTopologyType, GridSpec, GridTensorType, IndexMapType, InvariantTensorType, LatticeShiftType, LatticeType, RecordType, RepresentationLayout, ResolutionSpec, TupleType, VALUE_TYPE_SCHEMA_VERSION, ValueType, value_type_from_dict
from .v3_evolution import V3_FIRST_ROUND_MUTATION_VERSION, V3MutationAction, V3MutationRegion, V3MutationTarget, apply_v3_first_round_patch, build_v3_first_round_patch, choose_deterministic_v3_action, parse_v3_critic_response, parse_v3_router_response, v3_evolution_state, v3_first_round_mutation_catalog, v3_mutation_regions, v3_program_from_spec, v3_program_spec, v3_region_by_id, v3_region_for_field
from .v3_multifidelity import V3FidelityStage, V3MultiFidelityProtocol, rank_v3_stage_records
from .v3_structural_evolution import V3_STRUCTURAL_MUTATION_VERSION, V3StructuralAction, V3StructuralRegion, V3StructuralTarget, apply_v3_structural_patch, build_v3_structural_patch, choose_deterministic_v3_structural_action, v3_structural_mutation_catalog, v3_structural_novelty_report, v3_structural_regions

__all__ = [
    "ArchitectureProgram",
    "AffinePointType",
    "AxisSpec",
    "BACKEND_SEMANTICS_VERSION",
    "Carrier",
    "CategoricalTensorType",
    "AvailableValue",
    "CompletionAction",
    "CompletionDistance",
    "CostEstimate",
    "Compiler",
    "CanonicalSearchSurface",
    "CHECKPOINT_MAPPING_VERSION",
    "CheckpointMappingError",
    "CheckpointMappingManifest",
    "CheckpointTensorGroup",
    "LoweringPlan",
    "COMPILER_SEMANTICS_VERSION",
    "DSLValidationError",
    "DSLGenerationEngine",
    "Diagnostic",
    "EquivarianceLevel",
    "EquivariantTensorType",
    "EquivariantType",
    "ExplicitTopologyMigrationManifest",
    "ExplicitTopologyMigrationResult",
    "EvidenceItem",
    "EvidenceStore",
    "CapabilityProfile",
    "LeafFactorDefinition",
    "Frame",
    "FeatureRole",
    "HoleSink",
    "GroupSpec",
    "GraphTopologyType",
    "GridSpec",
    "GridTensorType",
    "GenerationResult",
    "InferenceResult",
    "InputPort",
    "IndexMapType",
    "InvariantTensorType",
    "Irrep",
    "Irreps",
    "LanguageVersion",
    "LatticeShiftType",
    "LatticeType",
    "LanguageEvolutionBoundary",
    "LanguageEvolutionPreregistration",
    "LanguageEvolutionResult",
    "LanguageReplayResult",
    "MotifDefinition",
    "MotifAdmissionRecord",
    "MotifDiscoveryPolicy",
    "MotifDiscoveryReport",
    "MotifProposal",
    "MotifRegistry",
    "MIGRATION_POLICY_VERSION",
    "Node",
    "OutputPort",
    "PrimitiveRegistry",
    "PatchEdit",
    "PARAMETER_CONTRACT_SCHEMA_VERSION",
    "ParameterAxis",
    "ParameterContract",
    "TypedPatch",
    "TypedHole",
    "TypedSubgraphOccurrence",
    "TypeChecker",
    "ResourceContract",
    "RecordType",
    "RepresentationLayout",
    "ReconstructedTensorContract",
    "ResolutionSpec",
    "RegionDefinition",
    "RewriteRuleDescriptor",
    "RewriteStep",
    "StrictRewriteResult",
    "SEARCH_SURFACE_VERSION",
    "TaskContract",
    "TupleType",
    "TypeMigrationManifest",
    "TypeMigrationResult",
    "VALUE_TYPE_SCHEMA_VERSION",
    "ValueType",
    "task_reasoning_context",
    "validate_task_reasoning",
    "architecture_id",
    "apply_typed_patch",
    "apply_strict_rewrites",
    "patch_protocol_schema",
    "canonicalize",
    "complete_typed_hole",
    "completion_repair_suggestions",
    "frozen_complement_hash",
    "discover_motif_proposals",
    "enumerate_typed_subgraphs",
    "fold_occurrence",
    "materialize_completion_patch",
    "program_completion_frontier",
    "core_registry",
    "describe_active_vocabulary",
    "describe_vocabulary_names",
    "default_canonical_search_surface",
    "enforce_static_resource_contract",
    "estimate_static_cost",
    "export_source_state_dict",
    "extract_checkpoint_state_dict",
    "equiformer_v1_capability_profile",
    "factor_by_region",
    "expand_motifs",
    "import_equiformer_v1",
    "import_equiformer_v3",
    "equiformer_v3_input_program",
    "equiformer_v3_attention_program",
    "equiformer_v3_backbone_program",
    "equiformer_v3_direct_model_program",
    "equiformer_v3_energy_head_program",
    "equiformer_v3_energy_model_program",
    "equiformer_v3_feed_forward_program",
    "equiformer_v3_force_head_program",
    "equiformer_v3_transblock_program",
    "legacy_equivariant_view",
    "migrate_program_v1_to_v2",
    "migrate_message_flow_to_explicit_topology",
    "migrate_task_contract_v1_to_v2",
    "migrate_value_type_v1_to_v2",
    "load_mapped_checkpoint_state_dict",
    "normalize_checkpoint_prefixes",
    "reference_motif_registry",
    "replay_motif_proposal",
    "parse_patch_response",
    "parse_planner_response",
    "parse_region_critic_response",
    "parse_region_router_response",
    "planner_prompt",
    "region_critic_prompt",
    "region_critic_repair_prompt",
    "region_router_prompt",
    "repair_prompt",
    "select_active_vocabulary",
    "strict_rewrite_registry_hash",
    "validate_region_transition",
    "validate_unique_factor_ownership",
    "v1_region_registry",
    "synthesizer_prompt",
    "translate_checkpoint_state_dict",
    "run_language_evolution_boundary",
    "value_type_from_dict",
    "VocabularyDecision",
    "CandidateLineageEvidence",
    "V3_FIRST_ROUND_MUTATION_VERSION",
    "V3MutationAction",
    "V3MutationRegion",
    "V3MutationTarget",
    "V3FidelityStage",
    "V3MultiFidelityProtocol",
    "V3_STRUCTURAL_MUTATION_VERSION",
    "V3StructuralAction",
    "V3StructuralRegion",
    "V3StructuralTarget",
    "apply_v3_first_round_patch",
    "apply_v3_structural_patch",
    "build_v3_first_round_patch",
    "build_v3_structural_patch",
    "choose_deterministic_v3_action",
    "choose_deterministic_v3_structural_action",
    "parse_v3_critic_response",
    "parse_v3_router_response",
    "rank_v3_stage_records",
    "v3_evolution_state",
    "v3_first_round_mutation_catalog",
    "v3_mutation_regions",
    "v3_program_from_spec",
    "v3_program_spec",
    "v3_region_by_id",
    "v3_region_for_field",
    "v3_structural_mutation_catalog",
    "v3_structural_novelty_report",
    "v3_structural_regions",
]
